### ISSUE TITLE
server error when you present (select) 2 or more verifiable credentials

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/qrcode-generator#12]
try by your self , if you select 2 verifiable credentials on the wallet to log in , there is a server error.

Because the json sent back by the wallet is in that case a list of several verifiable credentials and not just 1 VC

**Comment by zvjezdantasic** [comment]
would you explain in detail?

**Comment by ThierryThevenet** [comment]
You have to try by yourself with the wallet and more than one credential.
Go to https://talao.co/sandbox and collect at least 3 or 4 credentials
Then go to the generator and scan..
You will see that the mobile propose a list of credentials and you can select more than 1.
In that case the wallet send you a verifiable presentation with the attribute "verifiableCredential" as an array and not just as a json.
You can visualize what is sent it with our tool https://talao.co/wallet/test/display_VP...you will see an array
So lets say that in the case of multiple credentials, the generator must look for one in the array with "type" = "EmaiPass", if not reject

**Comment by ThierryThevenet** [comment]
This issue is not urgent, lest do the other ones before !!!!
