### ISSUE TITLE
change path on the QRcode and URL of the voucher

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/qrcode-generator#15]
When you get a voucher URL and QRcode it looks like as https://tezotopia.talao.co/62a9f684998e1828b846da73

it should be https://issuer.tezotopia.altme.io/issuer/dddddd

**Comment by zvjezdantasic** [comment]
https://issuer.tezotopia.altme.io/issuer/dddddd or https://issuer.tezotopia.altme.io/issuer/[62a9f684998e1828b846da73]?

**Comment by zvjezdantasic** [comment]
@ThierryThevenet

**Comment by ThierryThevenet** [comment]
https://issuer.tezotopia.altme.io/issuer/<voucher_id>
