### ISSUE TITLE
we cannot scroll the page

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/qrcode-generator#17]
![Capture d’écran de 2022-06-17 07-52-56](https://user-images.githubusercontent.com/32768069/174234237-1778faed-9f75-4f68-8fd6-381340a5d041.png)

**Comment by ThierryThevenet** [comment]
the page is larger than my screen

**Comment by zvjezdantasic** [comment]
I cannot reproduce it anymore
