### ISSUE TITLE
create a page to create and update a specific voucher for users coming from mobile

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/qrcode-generator#22]
th voucher_id is "voucher_mobile"

**Comment by ThierryThevenet** [comment]
We dont need a QR code and a link for that special voucher as the users come from the mobile directly

**Comment by ThierryThevenet** [comment]
the url to go to that page is https://issuer.tezotopia.altme.io/issuer/voucher_mobile 

voucher_id = voucher_mobile

**Comment by ThierryThevenet** [comment]
for this voucher the affiliate commission is 0%, affiliate email is contact@altme.io, name is Altme, affiliate blockchain is Tezos, affiliate account is Null
the only fields of the form are : voucher duration, gamer reward
teh voucher_id = voucher_mobile.

**Comment by ThierryThevenet** [comment]
the access to this voucher is probably in the first screen with radio button for voucher and membership card "voucher for mobile"

**Comment by zvjezdantasic** [comment]
okay
