### ISSUE TITLE
New credential : Tezotopia Loyalty card

### ISSUE THREAD

**Issue by thierry-thevenet** [TalaoDAO/qrcode-generator#56]
add this card in the chose screen
There is only one unique cerdential (as voucher mobile or Arago pass)
Only duration to setup in the credntial (fomr)

**Comment by ThierryThevenet** [comment]
the modele is https://github.com/TalaoDAO/wallet-tools/blob/main/test/CredentialOffer2/TezLoyaltyCard_1.jsonld
